/* global window */
window.WORKS = [
  {
    id: "deongkulche-mockup",
    title: "덩쿨체",
    category: "editorial",
    year: "",
    role: "",
    tags: ["Typography"],
    cover: "./dk5.png",
    images: ["./dk1.png", "./dk2.png", "./dk3.png", "./dk4.png"],
    description: "",
  },
  {
    id: "work-01",
    title: "Persona",
    category: "editorial",
    year: "",
    role: "",
    tags: ["Illustration"],
    coverFit: "contain",
    cover: "./Untitled-12-01.png",
    images: ["./Untitled-12-02.png", "./Untitled-12-03.png", "./Untitled-12-04.png"],
    description: "",
  },
  {
    id: "work-poster",
    title: "1인 가구 브랜딩 가이드",
    category: "editorial",
    year: "",
    role: "",
    tags: ["Infographic"],
    coverFit: "contain",
    cover: "./Untitled-13-01.png",
    images: ["./Untitled-13-02.png"],
    description: "",
  },
  {
    id: "sinjido-manual",
    title: "신지도 지역 브랜드 디자인",
    category: "digital",
    year: "",
    role: "",
    tags: ["Brand Design"],
    cover: "./sinjido.png",
    images: ["./manual.mp4"],
    description: "",
  },
  {
    id: "work-07",
    title: "Complicated",
    category: "editorial",
    year: "",
    role: "",
    tags: ["Graphic Design"],
    cover: "./Untitled-12-07.png",
    images: [],
    description: "",
  },
];

window.WORKS_UX = [
  {
    id: "ux-work-14",
    title: "Ethnography",
    category: "editorial",
    year: "",
    role: "",
    tags: ["User Experience Design I"],
    cover: "./Untitled-14.png",
    images: ["./ethnography-02.png", "./ethnography-03.png?v=2", "./ethnography-04.png"],
    description: "",
  },
  {
    id: "ux-work-gdbd",
    title: "Good Design & Bad Design",
    category: "editorial",
    year: "",
    role: "",
    tags: ["User Experience Design I"],
    cover: "./gdbd.jpg",
    images: [
      "./gdbd1.jpg",
      "./gdbd2.jpg",
      "./gdbd3.jpg",
      "./gdbd4.jpg",
      "./gdbd5.jpg",
      "./gdbd6.jpg",
    ],
    description: "",
  },
  {
    id: "ux-work-interview",
    title: "Interview",
    category: "editorial",
    year: "",
    role: "",
    tags: ["User Experience Design I"],
    cover: "./interview.png",
    images: ["./interview-04.png?v=2"],
    description: "",
  },
];
